modLoader="javafml"
loaderVersion="[33,)"
license="MIT License"
[[mods]]
modId="harderbranchmining"
version="${file.jarVersion}"
displayName="Harder Branch Mining Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/harder-branch-mining"
updateJSONURL="https://github.com/mactso/HarderBranchMining/raw/master/update.json"
logoFile="HBM-Logo.png"
authors="MacTso, Lupicus"
description='''Harder Branch Mining Mod.'''
[[dependencies.hbm]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hbm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,1.17.0)"
    ordering="NONE"
    side="BOTH"
