modLoader="javafml"
loaderVersion="[46,)"
license="MIT License"
[[mods]]
modId="harderbranchmining"
version="${file.jarVersion}"
displayName="Harder Branch Mining Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/harder-branch-mining"
updateJSONURL="https://github.com/mactso/HarderBranchMining/raw/main/update.json"
logoFile="HBM-Logo.png"
authors="MacTso, Lupicus"
description='''Harder Branch Mining Mod.'''
[[dependencies.harderbranchmining]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.harderbranchmining]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
